services:
  - type: web
    name: nomad-gps
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: embedded